notification_firebase.settings:
  type: config_object
  label: 'Notification Firebase settings'
  mapping:
    firebase_server_key:
      type: string
      label: 'Firebase server key'
    firebase_apiKey_id:
      type: string
      label: 'Firebase API Key'
    firebase_project_id:
      type: string
      label: 'Firebase project id'
    firebase_sender_id:
      type: string
      label: 'Firebase sender ID'
    firebase_app_id:
      type: string
      label: 'Firebase app Key'
dependencies:
  module:
    - notification_firebase
  enforced:
    module:
      - notification_firebase