<?php
// chèn css, js vào cuối tất cả các trang
function erp_user_dashboard_page_attachments_alter(array &$attachments){
    //$attachments['#attached']['library'][] = 'notification_firebase/notification_firebase'; // tên module/tên libraries
}

// chèn code vào tất cả các trang
function erp_user_dashboard_page_attachments(array &$attachments) {
    // chèn vào head
    $attachments['#attached']['html_head'][] = [
        [
          '#type' => 'html_tag',
          '#tag' => 'meta',
          '#attributes' => [
            'name' => 'generator',
            'content' => 'Mantan v1.6',
          ],
        ],
        'meta-generator',
    ];

    // chèn html
    //$attachments['#markup'].= '<b>Test</b>';
}

// khai báo sử dụng giao diện
function erp_user_dashboard_theme($existing, $type, $theme, $path) {
    // Store Kanban preprocess theme functions in a separate .inc file.
    \Drupal::moduleHandler()->loadInclude('erp_user_dashboard', 'inc', 'erp_user_dashboard.theme');

    return array(
        'erp_user_dashboard_dashboard' => array(
          'variables' => [
            'listBlock' => [],
          ],
        ),
    );
}


